on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This step checks out your code from the repository
      - name: Set up Git
        run: |
          git config user.name "wisdom"
          git config user.email "your.email@example.com"
